import type { Product } from "./types";

/** All 12 products from the design mockup, verbatim Bengali content */
export const PRODUCTS: Product[] = [
  {
    id: "gpt",
    slug: "chatgpt-plus",
    nameBn: "ChatGPT Plus",
    category: "AI Tools",
    mark: "GPT",
    monthlyPrice: 1150,
    isOneTime: false,
    unitLabel: "",
    badge: "ইনস্ট্যান্ট",
    deliveryEta: "ইনস্ট্যান্ট",
    stock: 34,
    aboutBn:
      "নিজের মেইলে প্রাইভেট ChatGPT Plus — শেয়ারিং নেই। GPT-5, ফাইল আপলোড, ইমেজ জেনারেশন আর Advanced Voice, সব আনলিমিটেড।",
    metaBn: "এআই টুলস · প্রাইভেট মেইল",
    specs: [
      { k: "অ্যাকাউন্ট", v: "প্রাইভেট" },
      { k: "শেয়ারিং", v: "নেই" },
      { k: "ডেলিভারি", v: "ইনস্ট্যান্ট" },
      { k: "রিজিয়ন", v: "গ্লোবাল" },
    ],
    includes: [
      "নিজের মেইলে অ্যাকাউন্ট — পাসওয়ার্ড আপনি চেঞ্জ করতে পারবেন",
      "GPT-5 আর রিজনিং মডেলে ফুল অ্যাক্সেস",
      "Advanced Voice, ফাইল আপলোড, ইমেজ জেনারেশন",
      "টার্ম শেষ হওয়ার আগে সমস্যা হলেই ফ্রি রিপ্লেসমেন্ট",
    ],
  },
  {
    id: "claude",
    slug: "claude-pro",
    nameBn: "Claude Pro",
    category: "AI Tools",
    mark: "CL",
    monthlyPrice: 1250,
    isOneTime: false,
    unitLabel: "",
    badge: "−১৮%",
    wasPrice: 1520,
    deliveryEta: "ইনস্ট্যান্ট",
    stock: 21,
    aboutBn:
      "Claude Pro প্রাইভেট অ্যাকাউন্টে — লম্বা ডকুমেন্ট, কোড আর রিসার্চের জন্য। Projects আর Artifacts সহ পূর্ণ অ্যাক্সেস।",
    metaBn: "এআই টুলস · প্রাইভেট মেইল",
    specs: [
      { k: "অ্যাকাউন্ট", v: "প্রাইভেট" },
      { k: "শেয়ারিং", v: "নেই" },
      { k: "ডেলিভারি", v: "ইনস্ট্যান্ট" },
      { k: "রিজিয়ন", v: "গ্লোবাল" },
    ],
    includes: [
      "প্রাইভেট অ্যাকাউন্ট, আপনার নিজের মেইলে",
      "Projects, Artifacts আর ফুল কনটেক্সট উইন্ডো",
      "ফ্রি প্ল্যানের চেয়ে ৫ গুণ বেশি ব্যবহার",
      "পুরো টার্মে রিপ্লেসমেন্ট ওয়ারেন্টি",
    ],
  },
  {
    id: "netflix",
    slug: "netflix-premium",
    nameBn: "Netflix Premium",
    category: "Streaming",
    mark: "N",
    monthlyPrice: 320,
    isOneTime: false,
    unitLabel: "",
    badge: "4K UHD",
    deliveryEta: "≤ ৩০ মিনিট",
    stock: 48,
    aboutBn:
      "৪কে আলট্রা এইচডি Netflix — নিজের আলাদা প্রোফাইল, কেউ ঘাঁটবে না। পিন দিয়ে লক করা থাকবে।",
    metaBn: "স্ট্রিমিং · নিজের প্রোফাইল",
    specs: [
      { k: "কোয়ালিটি", v: "4K UHD" },
      { k: "প্রোফাইল", v: "নিজের" },
      { k: "স্ক্রিন", v: "একসাথে ১টি" },
      { k: "ডেলিভারি", v: "≤ ৩০ মিনিট" },
    ],
    includes: [
      "নিজের প্রোফাইল, পিন দিয়ে লক করা",
      "4K UHD + HDR + Dolby Atmos",
      "মোবাইল, টিভি, ল্যাপটপ — যেখানে চান",
      "প্রোফাইলে সমস্যা হলেই সঙ্গে সঙ্গে রিপ্লেস",
    ],
  },
  {
    id: "yt",
    slug: "youtube-premium",
    nameBn: "YouTube Premium",
    category: "Streaming",
    mark: "YT",
    monthlyPrice: 190,
    isOneTime: false,
    unitLabel: "",
    badge: "হট",
    deliveryEta: "ইনস্ট্যান্ট",
    stock: 62,
    aboutBn:
      "বিজ্ঞাপন ছাড়া YouTube, ব্যাকগ্রাউন্ড প্লে আর YouTube Music — আপনার নিজের জিমেইলেই ইনভাইট।",
    metaBn: "স্ট্রিমিং · আপনার মেইল",
    specs: [
      { k: "ইনভাইট", v: "আপনার জিমেইল" },
      { k: "বিজ্ঞাপন", v: "নেই" },
      { k: "মিউজিক", v: "সহ" },
      { k: "ডেলিভারি", v: "ইনস্ট্যান্ট" },
    ],
    includes: [
      "আপনার নিজের জিমেইলে ইনভাইট",
      "বিজ্ঞাপনহীন ভিডিও + ব্যাকগ্রাউন্ড প্লে",
      "YouTube Music Premium ফ্রি",
      "ডাউনলোড করে অফলাইনে দেখুন",
    ],
  },
  {
    id: "spotify",
    slug: "spotify-premium",
    nameBn: "Spotify Premium",
    category: "Streaming",
    mark: "SP",
    monthlyPrice: 150,
    isOneTime: false,
    unitLabel: "",
    badge: "ইনস্ট্যান্ট",
    deliveryEta: "ইনস্ট্যান্ট",
    stock: 55,
    aboutBn:
      "Spotify Premium ইনডিভিজুয়াল প্ল্যান — নিজের অ্যাকাউন্টেই, প্লেলিস্ট হারাবে না।",
    metaBn: "স্ট্রিমিং · আপনার মেইল",
    specs: [
      { k: "প্ল্যান", v: "ইনডিভিজুয়াল" },
      { k: "অ্যাকাউন্ট", v: "আপনার" },
      { k: "কোয়ালিটি", v: "৩২০ kbps" },
      { k: "ডেলিভারি", v: "ইনস্ট্যান্ট" },
    ],
    includes: [
      "নিজের অ্যাকাউন্টেই আপগ্রেড — প্লেলিস্ট থাকবে",
      "বিজ্ঞাপনহীন, অফলাইন ডাউনলোড",
      "৩২০ kbps কোয়ালিটি",
      "পুরো টার্মে ওয়ারেন্টি",
    ],
  },
  {
    id: "canva",
    slug: "canva-pro",
    nameBn: "Canva Pro",
    category: "Design",
    mark: "CV",
    monthlyPrice: 145,
    isOneTime: false,
    unitLabel: "",
    badge: "সেরা দাম",
    deliveryEta: "ইনস্ট্যান্ট",
    stock: 71,
    aboutBn:
      "নিজের Canva অ্যাকাউন্টেই Pro — সব প্রিমিয়াম টেমপ্লেট, ব্র্যান্ড কিট আর ব্যাকগ্রাউন্ড রিমুভার।",
    metaBn: "ডিজাইন · আপনার অ্যাকাউন্ট",
    specs: [
      { k: "ইনভাইট", v: "আপনার অ্যাকাউন্ট" },
      { k: "স্টোরেজ", v: "১ টিবি" },
      { k: "টেমপ্লেট", v: "সব প্রো" },
      { k: "ডেলিভারি", v: "ইনস্ট্যান্ট" },
    ],
    includes: [
      "আপনার নিজের অ্যাকাউন্টে প্রো ইনভাইট",
      "সব প্রিমিয়াম টেমপ্লেট আর এলিমেন্ট",
      "ব্যাকগ্রাউন্ড রিমুভার, Magic Studio",
      "১ টিবি ক্লাউড স্টোরেজ",
    ],
  },
  {
    id: "adobe",
    slug: "adobe-creative-cloud",
    nameBn: "Adobe Creative Cloud",
    category: "Design",
    mark: "AD",
    monthlyPrice: 1690,
    isOneTime: false,
    unitLabel: "",
    badge: "সব অ্যাপ",
    deliveryEta: "≤ ২ ঘণ্টা",
    stock: 12,
    aboutBn:
      "পুরো Adobe Creative Cloud — Photoshop, Illustrator, Premiere Pro সহ ২০+ অ্যাপ, ১০০ জিবি স্টোরেজ।",
    metaBn: "ডিজাইন · সব অ্যাপ",
    specs: [
      { k: "অ্যাপ", v: "২০+" },
      { k: "স্টোরেজ", v: "১০০ জিবি" },
      { k: "ফন্ট", v: "সহ" },
      { k: "ডেলিভারি", v: "≤ ২ ঘণ্টা" },
    ],
    includes: [
      "Photoshop, Illustrator, Premiere, After Effects",
      "Adobe Fonts আর Stock টেমপ্লেট",
      "১০০ জিবি ক্লাউড স্টোরেজ",
      "আসল লাইসেন্স, ওয়ারেন্টি সহ",
    ],
  },
  {
    id: "grammarly",
    slug: "grammarly-premium",
    nameBn: "Grammarly Premium",
    category: "Design",
    mark: "GR",
    monthlyPrice: 320,
    isOneTime: false,
    unitLabel: "",
    badge: "ইনস্ট্যান্ট",
    deliveryEta: "ইনস্ট্যান্ট",
    stock: 29,
    aboutBn:
      "Grammarly Premium — অ্যাডভান্সড গ্রামার, টোন আর প্লেজিয়ারিজম চেক, নিজের মেইলেই।",
    metaBn: "রাইটিং · আপনার মেইল",
    specs: [
      { k: "অ্যাকাউন্ট", v: "প্রাইভেট" },
      { k: "প্লেজিয়ারিজম", v: "সহ" },
      { k: "টোন", v: "অ্যাডভান্সড" },
      { k: "ডেলিভারি", v: "ইনস্ট্যান্ট" },
    ],
    includes: [
      "অ্যাডভান্সড গ্রামার আর ক্ল্যারিটি সাজেশন",
      "প্লেজিয়ারিজম চেকার",
      "টোন আর রিরাইট সাজেশন",
      "পুরো টার্মে রিপ্লেসমেন্ট",
    ],
  },
  {
    id: "ff",
    slug: "free-fire-diamond",
    nameBn: "Free Fire Diamond",
    category: "Gaming",
    mark: "FF",
    monthlyPrice: 85,
    isOneTime: true,
    unitLabel: "/ ১০০ ডায়া",
    badge: "টপ-আপ",
    deliveryEta: "ইনস্ট্যান্ট",
    stock: 999,
    aboutBn:
      "UID দিলেই ডায়মন্ড — লগইন লাগবে না, ৫ মিনিটে অ্যাকাউন্টে ঢুকে যাবে।",
    metaBn: "গেমিং · UID টপ-আপ",
    specs: [
      { k: "পদ্ধতি", v: "UID টপ-আপ" },
      { k: "লগইন", v: "লাগবে না" },
      { k: "রেট", v: "৳৮৫ / ১০০" },
      { k: "ডেলিভারি", v: "ইনস্ট্যান্ট" },
    ],
    includes: [
      "শুধু UID দিলেই হবে",
      "লগইন ডিটেইলস লাগবে না",
      "বাল্ক অর্ডারে এক্সট্রা ডিসকাউন্ট",
      "না ঢুকলে ফুল রিফান্ড",
    ],
  },
  {
    id: "pubg",
    slug: "pubg-mobile-uc",
    nameBn: "PUBG Mobile UC",
    category: "Gaming",
    mark: "UC",
    monthlyPrice: 92,
    isOneTime: true,
    unitLabel: "/ ৬০ UC",
    badge: "টপ-আপ",
    deliveryEta: "ইনস্ট্যান্ট",
    stock: 999,
    aboutBn:
      "PUBG Mobile UC — ক্যারেক্টার আইডি দিলেই ৫ মিনিটে টপ-আপ।",
    metaBn: "গেমিং · UID টপ-আপ",
    specs: [
      { k: "পদ্ধতি", v: "ক্যারেক্টার আইডি" },
      { k: "লগইন", v: "লাগবে না" },
      { k: "রেট", v: "৳৯২ / ৬০ UC" },
      { k: "ডেলিভারি", v: "ইনস্ট্যান্ট" },
    ],
    includes: [
      "ক্যারেক্টার আইডি দিলেই টপ-আপ",
      "Royale Pass-ও করা যাবে",
      "বাল্ক রেট আছে",
      "না ঢুকলে ফুল রিফান্ড",
    ],
  },
  {
    id: "steam",
    slug: "steam-gift-card",
    nameBn: "Steam Gift Card",
    category: "Gift cards",
    mark: "ST",
    monthlyPrice: 1450,
    isOneTime: true,
    unitLabel: "/ $১০",
    badge: "গিফট",
    deliveryEta: "ইনস্ট্যান্ট",
    stock: 40,
    aboutBn:
      "Steam ওয়ালেট কোড — গ্লোবাল রিজিয়ন, স্ক্র্যাচ করে সাথে সাথে রিডিম।",
    metaBn: "গিফট কার্ড · গ্লোবাল কোড",
    specs: [
      { k: "রিজিয়ন", v: "গ্লোবাল" },
      { k: "ধরন", v: "ওয়ালেট কোড" },
      { k: "ভ্যালু", v: "$১০" },
      { k: "ডেলিভারি", v: "ইনস্ট্যান্ট" },
    ],
    includes: [
      "গ্লোবাল রিজিয়ন কোড",
      "হোয়াটসঅ্যাপে কোড চলে আসবে",
      "রিডিম না হলে রিপ্লেস",
      "বড় অ্যামাউন্টও আছে",
    ],
  },
  {
    id: "gplay",
    slug: "google-play-gift-card",
    nameBn: "Google Play Gift Card",
    category: "Gift cards",
    mark: "GP",
    monthlyPrice: 1380,
    isOneTime: true,
    unitLabel: "/ $১০",
    badge: "গিফট",
    deliveryEta: "ইনস্ট্যান্ট",
    stock: 33,
    aboutBn:
      "Google Play গিফট কার্ড — ইউএস রিজিয়ন কোড, অ্যাপ আর ইন-অ্যাপ পারচেজে চলবে।",
    metaBn: "গিফট কার্ড · ইউএস রিজিয়ন",
    specs: [
      { k: "রিজিয়ন", v: "ইউএস" },
      { k: "ধরন", v: "গিফট কোড" },
      { k: "ভ্যালু", v: "$১০" },
      { k: "ডেলিভারি", v: "ইনস্ট্যান্ট" },
    ],
    includes: [
      "ইউএস রিজিয়ন গিফট কোড",
      "অ্যাপ, গেম আর ইন-অ্যাপ পারচেজ",
      "ইনস্ট্যান্ট হোয়াটসঅ্যাপ ডেলিভারি",
      "রিডিম না হলে রিপ্লেস",
    ],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
